### ISSUE TITLE
Permisos de escritura sobre el repositorio

### ISSUE THREAD

**Issue by f3-d3** [vidapogosoft/NetCore092021#1]
Buenas noches Victor,

Ayúdame otorgándole permisos de escritura a mi usuario de Git-Hub, para subir mis cambios.
Error:
`Remote: Permission to vidapogosoft/NetCore092021.git denied to f3-d3.
Se produjo un error al insertar en el repositorio remoto: Git failed with a fatal error.`

Gracias,

**Comment by vidapogosoft** [comment]
Listo te puse como colaborador del repositorio para que puedas subir cambios, me confirma si los pudo subir. Gracias por su aporte.
